<?php

namespace Web\EntityBundle\Repository;

/**
 * SaveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaveRepository extends \Doctrine\ORM\EntityRepository
{
}
