app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

main:
    resource: "@MainBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

entity:
    resource: "@EntityBundle/Controller/"
    type:     annotation
    prefix:   /





